version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoke_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: php -S 0.0.0.0:8000 -t public
    depends_on:
      - db
    ports:
      - "9999:9999"  # Allow stub server to be reached via localhost
      - "8000:8000"
    environment:
      APP_ENV: dev
      DATABASE_URL: postgresql://app:!ChangeMe!@db:5432/app?serverVersion=16&charset=utf8


  # todo: change for prod env file values should be passed to it.
  db:
    image: postgres:16-alpine
    container_name: invoke_db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: '!ChangeMe!'
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "app", "-U", "app"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
