name: "Funny One"
schedule: "50 11 * * *"
url: "http://localhost:9999"
method: POST
payload:
  keep_days: 30
headers:
  Authorization:
    env:
      valueFrom: "CronValueProviders\\ApiEndpointTokenProvider"
enabled: true
